# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicfile', models.TextField(blank=True, verbose_name='FileName. Add the full name of mp3 file. Exchange space into "_"')),
                ('name', models.TextField(blank=True, verbose_name='Song Name')),
                ('artist', models.TextField(blank=True, verbose_name='Artist Name')),
                ('music', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Music')),
            ],
        ),
        migrations.CreateModel(
            name='MusicPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=255)),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='music', verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='musical',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.MusicPost'),
        ),
    ]
