# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musical',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='media/music', verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/music', verbose_name='Image'),
        ),
    ]
