# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/yoga')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.YogaPost')),
            ],
        ),
    ]
