# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_yogaimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaimg',
            name='title',
        ),
        migrations.AddField(
            model_name='yogapost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/yoga'),
        ),
        migrations.DeleteModel(
            name='YogaImg',
        ),
    ]
