# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160505_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogapost',
            name='image',
            field=models.ImageField(blank=True, upload_to='/media/yoga'),
        ),
    ]
